-- AlterTable
ALTER TABLE "Entry" ADD COLUMN     "percentage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "volume" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "defaultPercentage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "defaultVolume" INTEGER NOT NULL DEFAULT 0;
